name: Release

on:
  push:
    branches:
      - main
      - beta
      - next
      - 3.x
  pull_request:
  workflow_dispatch:
    inputs:
      name: 
        type: choice
        description: Package name (npm)
        options:
        - "@auth/core"
        - "@auth/nextjs"
        - "@auth/dgraph-adapter"
        - "@auth/drizzle-adapter"
        - "@auth/dynamodb-adapter"
        - "@auth/fauna-adapter"
        - "@auth/firebase-adapter"
        - "@auth/mikro-orm-adapter"
        - "@auth/mongodb-adapter"
        - "@auth/neo4j-adapter"
        - "@auth/pouchdb-adapter"
        - "@auth/prisma-adapter"
        - "@auth/sequelize-adapter"
        - "@auth/supabase-adapter"
        - "@auth/typeorm-adapter"
        - "@auth/upstash-redis-adapter"
        - "@auth/xata-adapter"
        - "next-auth"
      path:
        type: choice
        description: Directory name (packages/*)
        options:
        - "core"
        - "frameworks-nextjs"
        - "adapter-dgraph"
        - "adapter-drizzle"
        - "adapter-dynamodb"
        - "adapter-fauna"
        - "adapter-firebase"
        - "adapter-mikro-orm"
        - "adapter-mongodb"
        - "adapter-neo4j"
        - "adapter-pouchdb"
        - "adapter-prisma"
        - "adapter-sequelize"
        - "adapter-supabase"
        - "adapter-typeorm"
        - "adapter-upstash-redis"
        - "adapter-xata"
        - "next-auth"
env:
  FORCE_COLOR: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Init
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      - name: Upload Turbo artifacts
        uses: actions/upload-artifact@v3
        with:
          name: turbo-report
          path: .turbo/runs/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
